services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firmable-backend
    ports:
      - "3000:3000"
    env_file:
      - ./config.env
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - firmable-network

networks:
  firmable-network:
    driver: bridge
